# Generated by Django 4.2.4 on 2023-09-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan',
            field=models.CharField(choices=[('B', 'Basic'), ('P', 'Pro')], default='B', max_length=1),
        ),
    ]
