# Generated by Django 4.2.4 on 2023-09-07 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_customer_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='credit_hours',
            new_name='credit_minutes',
        ),
    ]
