# Generated by Django 4.2.4 on 2023-09-12 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.TextField(unique=True)),
                ('expires', models.DateTimeField()),
                ('token', models.TextField()),
            ],
        ),
    ]
