# Generated by Django 4.2.4 on 2023-09-02 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamliststatus',
            options={'ordering': ['-stream_list__created_at', '-created_at'], 'verbose_name': 'StreamListStatus'},
        ),
        migrations.AlterField(
            model_name='medialivechannel',
            name='state',
            field=models.CharField(choices=[('C', 'Created'), ('R', 'Running'), ('S', 'Stopping'), ('T', 'Stopped'), ('D', 'Deleted')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='stream_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='streamlist.streamlist'),
        ),
    ]
