# Generated by Django 4.2.4 on 2023-09-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0002_alter_streamliststatus_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamlist',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
