# Generated by Django 4.2.4 on 2023-08-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0003_mediaconvertjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaconvertjob',
            options={'verbose_name': 'MediaConvertJob'},
        ),
        migrations.AlterModelOptions(
            name='streamlist',
            options={'verbose_name': 'StreamList'},
        ),
        migrations.AlterModelOptions(
            name='streamvideo',
            options={'verbose_name': 'StreamVideo'},
        ),
        migrations.AddField(
            model_name='video',
            name='ordering',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
