# Generated by Django 4.2.4 on 2023-09-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0004_alter_streamlist_title_alter_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.TextField(),
        ),
    ]
