# Generated by Django 4.2.4 on 2023-08-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0004_alter_mediaconvertjob_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['stream_list', 'ordering']},
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('U', 'Uploading'), ('D', 'Uploaded'), ('E', 'Error')], default='U', max_length=1),
        ),
    ]
