# Generated by Django 4.2.4 on 2023-09-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0005_alter_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamvideo',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('D', 'Deleted'), ('E', 'Error')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('U', 'Uploaded'), ('D', 'Deleted'), ('E', 'Error')], default='C', max_length=1),
        ),
    ]
