# Generated by Django 4.2.4 on 2023-08-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0005_alter_video_options_video_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaconvertjob',
            name='user',
        ),
        migrations.AddField(
            model_name='streamlist',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('P', 'Progressing'), ('R', 'Ready'), ('E', 'Error')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='mediaconvertjob',
            name='stream_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='streamlist.streamlist'),
        ),
    ]
