# Generated by Django 4.2.4 on 2023-08-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0007_streamvideo_duration_in_ms_alter_streamlist_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamvideo',
            name='size',
        ),
    ]
