# Generated by Django 4.2.4 on 2023-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0007_medialivechannel_stop_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streamlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'StreamList'},
        ),
        migrations.AddField(
            model_name='streamlist',
            name='credit_minutes_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
