# Generated by Django 4.2.4 on 2023-08-30 10:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0008_remove_streamvideo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamlist',
            name='stream_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mediaconvertjob',
            name='stream_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_convert_job', to='streamlist.streamlist'),
        ),
        migrations.AlterField(
            model_name='streamlist',
            name='status',
            field=models.CharField(choices=[('Q', 'Queued'), ('P', 'Processing'), ('R', 'Ready'), ('S', 'Streaming'), ('F', 'Finished'), ('C', 'Cancelled'), ('E', 'Error')], default='Q', max_length=1),
        ),
        migrations.AlterField(
            model_name='streamvideo',
            name='stream_list',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stream_video', to='streamlist.streamlist'),
        ),
        migrations.CreateModel(
            name='MediaLiveChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_id', models.CharField(blank=True, max_length=100, null=True)),
                ('input_id', models.CharField(max_length=100)),
                ('stream_key', models.CharField(max_length=100)),
                ('audio_description_name', models.CharField(max_length=100)),
                ('video_description_name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('C', 'Created'), ('R', 'Running')], default='C', max_length=1)),
                ('stream_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_live_channel', to='streamlist.streamlist')),
            ],
            options={
                'verbose_name': 'MediaLiveChannel',
            },
        ),
    ]
