# Generated by Django 4.2.4 on 2023-09-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamlist', '0008_alter_streamlist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaconvertjob',
            options={'ordering': ['stream_list'], 'verbose_name': 'MediaConvertJob'},
        ),
        migrations.AlterModelOptions(
            name='medialivechannel',
            options={'ordering': ['stream_list'], 'verbose_name': 'MediaLiveChannel'},
        ),
        migrations.AlterModelOptions(
            name='streamliststatus',
            options={'ordering': ['stream_list', '-created_at'], 'verbose_name': 'StreamListStatus'},
        ),
        migrations.AlterModelOptions(
            name='streamvideo',
            options={'ordering': ['stream_list'], 'verbose_name': 'StreamVideo'},
        ),
    ]
